"""Role-scoped tools. Names mapped per family. Missing names are skipped, never invented as installs."""

from __future__ import annotations

from dataclasses import dataclass

from tessera.models import DistroFamily, RoleId

Family = DistroFamily


@dataclass(frozen=True)
class Pkg:
    id: str
    roles: tuple[RoleId, ...]
    summary_it: str
    summary_en: str
    names: dict[DistroFamily, str | None]
    aur: str | None = None
    flatpak: str | None = None
    pipx: str | None = None
    kali_only: bool = False
    blackarch: str | None = None
    recommended: bool = True
    heavy: bool = False  # skip on < 8 GiB unless forced
    legal: str = "lab"  # lab = authorized testing / daily = everyday


def n(
    default: str | None = None,
    *,
    debian: str | None = None,
    ubuntu: str | None = None,
    kali: str | None = None,
    arch: str | None = None,
    fedora: str | None = None,
    rhel: str | None = None,
    suse: str | None = None,
    alpine: str | None = None,
    void: str | None = None,
    gentoo: str | None = None,
    nixos: str | None = None,
) -> dict[DistroFamily, str | None]:
    """Fill every family. Explicit None means 'not packaged here'."""
    deb = debian if debian is not None else default
    ubu = ubuntu if ubuntu is not None else deb
    kal = kali if kali is not None else ubu
    fed = fedora if fedora is not None else default
    return {
        DistroFamily.DEBIAN: deb,
        DistroFamily.UBUNTU: ubu,
        DistroFamily.KALI: kal,
        DistroFamily.ARCH: arch if arch is not None else default,
        DistroFamily.FEDORA: fed,
        DistroFamily.RHEL: rhel if rhel is not None else fed,
        DistroFamily.SUSE: suse if suse is not None else default,
        DistroFamily.ALPINE: alpine if alpine is not None else default,
        DistroFamily.VOID: void if void is not None else default,
        DistroFamily.GENTOO: gentoo if gentoo is not None else default,
        DistroFamily.NIXOS: nixos if nixos is not None else default,
        DistroFamily.UNKNOWN: default,
    }


PACKAGES: tuple[Pkg, ...] = (
    # ── daily ──────────────────────────────────────────────────────────
    Pkg("git", (RoleId.DAILY, RoleId.DEVELOPER, RoleId.CYBER, RoleId.OPS, RoleId.DATA),
        "Controllo versione", "Version control", n("git"), recommended=True),
    Pkg("curl", (RoleId.DAILY, RoleId.DEVELOPER, RoleId.CYBER, RoleId.OPS),
        "Client HTTP", "HTTP client", n("curl")),
    Pkg("wget", (RoleId.DAILY, RoleId.DEVELOPER, RoleId.OPS),
        "Download file", "File download", n("wget")),
    Pkg("jq", (RoleId.DEVELOPER, RoleId.OPS, RoleId.CYBER, RoleId.DATA),
        "JSON in shell", "JSON in the shell", n("jq")),
    Pkg("ripgrep", (RoleId.DEVELOPER, RoleId.CYBER, RoleId.OPS),
        "Ricerca ricorsiva veloce", "Fast recursive search",
        n("ripgrep", alpine="ripgrep", gentoo="sys-apps/ripgrep"), aur="ripgrep"),
    Pkg("fd", (RoleId.DEVELOPER, RoleId.OPS),
        "Find moderno", "Modern find",
        n("fd-find", arch="fd", fedora="fd-find", alpine="fd", void="fd"), aur="fd"),
    Pkg("tmux", (RoleId.DEVELOPER, RoleId.OPS, RoleId.CYBER, RoleId.SERVER),
        "Multiplexer terminale", "Terminal multiplexer", n("tmux")),
    Pkg("neovim", (RoleId.DEVELOPER, RoleId.OPS, RoleId.CYBER),
        "Editor", "Editor", n("neovim")),
    Pkg("htop", (RoleId.DAILY, RoleId.OPS, RoleId.SERVER),
        "Processi interattivi", "Interactive processes", n("htop")),
    Pkg("keepassxc", (RoleId.DAILY, RoleId.PRIVACY, RoleId.CYBER, RoleId.DEVELOPER),
        "Database password cifrato", "Encrypted password database",
        n("keepassxc"), flatpak="org.keepassxc.KeePassXC"),
    Pkg("timeshift", (RoleId.DAILY,),
        "Istantanee di sistema (btrfs/rsync)", "System snapshots (btrfs/rsync)",
        n("timeshift", fedora=None, alpine=None, rhel=None), aur="timeshift"),
    Pkg("firefox", (RoleId.DAILY, RoleId.PRIVACY),
        "Browser", "Browser",
        n("firefox", debian="firefox-esr"), flatpak="org.mozilla.firefox"),
    Pkg("vlc", (RoleId.DAILY, RoleId.CREATIVE),
        "Lettore media", "Media player", n("vlc"), flatpak="org.videolan.VLC"),
    # ── developer ──────────────────────────────────────────────────────
    Pkg("build-essential", (RoleId.DEVELOPER, RoleId.CYBER),
        "Compilatore C/C++ e make", "C/C++ compiler and make",
        n("build-essential", arch="base-devel", fedora="gcc make gcc-c++",
          rhel="@development-tools", suse="devel_basis", alpine="build-base",
          void="base-devel", gentoo="sys-devel/gcc"), recommended=True),
    Pkg("cmake", (RoleId.DEVELOPER,),
        "Build system", "Build system", n("cmake")),
    Pkg("python3", (RoleId.DEVELOPER, RoleId.CYBER, RoleId.DATA, RoleId.OPS),
        "Python 3", "Python 3", n("python3", arch="python", alpine="python3")),
    Pkg("python3-venv", (RoleId.DEVELOPER, RoleId.DATA, RoleId.CYBER),
        "venv ufficiale", "Official venv",
        n("python3-venv", arch="python", fedora="python3", alpine="python3")),
    Pkg("pipx", (RoleId.DEVELOPER, RoleId.CYBER, RoleId.DATA),
        "Strumenti Python isolati", "Isolated Python tools",
        n("pipx")),
    Pkg("nodejs", (RoleId.DEVELOPER,),
        "Runtime JS", "JS runtime",
        n("nodejs", debian="nodejs", ubuntu="nodejs")),
    Pkg("npm", (RoleId.DEVELOPER,),
        "Pacchetti JS", "JS packages", n("npm")),
    Pkg("docker", (RoleId.DEVELOPER, RoleId.OPS, RoleId.CYBER),
        "Container engine (docker o podman)", "Container engine (docker or podman)",
        n("docker.io", arch="docker", fedora="docker", rhel="podman",
          suse="docker", alpine="docker", kali="docker.io"), heavy=True),
    Pkg("podman", (RoleId.DEVELOPER, RoleId.OPS),
        "Container rootless", "Rootless containers",
        n("podman"), heavy=True),
    Pkg("direnv", (RoleId.DEVELOPER,),
        "Env per directory", "Per-directory env", n("direnv")),
    Pkg("shellcheck", (RoleId.DEVELOPER, RoleId.OPS),
        "Linter bash", "Bash linter", n("shellcheck")),
    Pkg("strace", (RoleId.DEVELOPER, RoleId.CYBER, RoleId.OPS),
        "Trace syscall", "Syscall trace", n("strace")),
    Pkg("lsof", (RoleId.DEVELOPER, RoleId.CYBER, RoleId.OPS),
        "File aperti", "Open files", n("lsof")),
    Pkg("gdb", (RoleId.DEVELOPER, RoleId.CYBER),
        "Debugger", "Debugger", n("gdb")),
    Pkg("postgresql-client", (RoleId.DEVELOPER, RoleId.DATA, RoleId.OPS),
        "Client PostgreSQL", "PostgreSQL client",
        n("postgresql-client", arch="postgresql", fedora="postgresql", alpine="postgresql-client")),
    Pkg("sqlite3", (RoleId.DEVELOPER, RoleId.DATA, RoleId.CYBER),
        "SQLite CLI", "SQLite CLI", n("sqlite3", arch="sqlite", fedora="sqlite")),
    Pkg("httpie", (RoleId.DEVELOPER, RoleId.OPS),
        "HTTP umano", "Human HTTP", n("httpie")),
    Pkg("gh", (RoleId.DEVELOPER,),
        "CLI GitHub", "GitHub CLI",
        n("gh", debian=None), aur="github-cli"),
    Pkg("glab", (RoleId.DEVELOPER,),
        "CLI GitLab", "GitLab CLI",
        n(None, arch="glab", fedora="glab"), aur="glab"),
    # ── ops ────────────────────────────────────────────────────────────
    Pkg("ansible", (RoleId.OPS, RoleId.DEVELOPER),
        "Automazione", "Automation", n("ansible"), heavy=True),
    Pkg("terraform", (RoleId.OPS,),
        "IaC", "IaC",
        n(None, arch="terraform", fedora="terraform"), aur="terraform"),
    Pkg("kubectl", (RoleId.OPS, RoleId.DEVELOPER),
        "Kubernetes CLI", "Kubernetes CLI",
        n("kubernetes-client", arch="kubectl", fedora="kubernetes-client"), aur="kubectl"),
    Pkg("helm", (RoleId.OPS,),
        "Chart Kubernetes", "Kubernetes charts",
        n(None, arch="helm", fedora="helm"), aur="helm"),
    Pkg("rsync", (RoleId.OPS, RoleId.DAILY, RoleId.SERVER),
        "Sincronizza file", "File sync", n("rsync")),
    Pkg("nftables", (RoleId.OPS, RoleId.SERVER, RoleId.PRIVACY, RoleId.CYBER),
        "Firewall nft", "nft firewall", n("nftables")),
    Pkg("fail2ban", (RoleId.OPS, RoleId.SERVER, RoleId.PRIVACY),
        "Ban tentativi ripetuti", "Ban repeated attempts", n("fail2ban")),
    Pkg("journalctl-less", (RoleId.OPS, RoleId.SERVER),
        "Meno è già systemd", "less is already systemd",
        n(None), recommended=False),
    # ── data ───────────────────────────────────────────────────────────
    Pkg("jupyter", (RoleId.DATA, RoleId.DEVELOPER),
        "Notebook", "Notebooks",
        n("jupyter-notebook", arch="jupyter-notebook", fedora="python3-jupyter-core"),
        pipx="jupyter", heavy=True),
    Pkg("r-base", (RoleId.DATA,),
        "R", "R",
        n("r-base", arch="r", fedora="R", alpine=None), heavy=True),
    Pkg("python3-numpy", (RoleId.DATA, RoleId.DEVELOPER),
        "Numerics", "Numerics",
        n("python3-numpy", arch="python-numpy", fedora="python3-numpy")),
    # ── creative ───────────────────────────────────────────────────────
    Pkg("gimp", (RoleId.CREATIVE,),
        "Raster", "Raster", n("gimp"), flatpak="org.gimp.GIMP", heavy=True),
    Pkg("inkscape", (RoleId.CREATIVE,),
        "Vettoriale", "Vector", n("inkscape"), flatpak="org.inkscape.Inkscape", heavy=True),
    Pkg("obs-studio", (RoleId.CREATIVE,),
        "Registrazione / streaming", "Recording / streaming",
        n("obs-studio"), flatpak="com.obsproject.Studio", heavy=True),
    Pkg("blender", (RoleId.CREATIVE,),
        "3D", "3D", n("blender"), flatpak="org.blender.Blender", heavy=True),
    Pkg("audacity", (RoleId.CREATIVE,),
        "Audio", "Audio", n("audacity"), flatpak="org.audacityteam.Audacity"),
    Pkg("kdenlive", (RoleId.CREATIVE,),
        "Montaggio video", "Video editor", n("kdenlive"), flatpak="org.kde.kdenlive", heavy=True),
    # ── privacy ────────────────────────────────────────────────────────
    Pkg("firejail", (RoleId.PRIVACY, RoleId.DAILY),
        "Sandbox applicazioni", "Application sandbox", n("firejail")),
    Pkg("apparmor", (RoleId.PRIVACY, RoleId.SERVER),
        "MAC AppArmor", "AppArmor MAC",
        n("apparmor", fedora=None, rhel=None, arch="apparmor")),
    Pkg("torbrowser-launcher", (RoleId.PRIVACY,),
        "Avvio Tor Browser (upstream signed)", "Tor Browser launcher (upstream signed)",
        n("torbrowser-launcher", fedora="torbrowser-launcher", alpine=None), aur="torbrowser-launcher"),
    Pkg("wireguard", (RoleId.PRIVACY, RoleId.OPS, RoleId.CYBER),
        "VPN WireGuard (client, tuoi endpoint)", "WireGuard VPN (client, your endpoints)",
        n("wireguard-tools")),
    Pkg("unbound", (RoleId.PRIVACY, RoleId.SERVER),
        "Resolver DNS locale", "Local DNS resolver", n("unbound")),
    # ── cyber: reconnaissance & defensive lab (authorized use) ─────────
    Pkg("nmap", (RoleId.CYBER, RoleId.OPS),
        "Scansione porte su target autorizzati", "Port scan on authorized targets",
        n("nmap"), legal="lab"),
    Pkg("masscan", (RoleId.CYBER,),
        "Scan asincrono (lab)", "Async scan (lab)",
        n("masscan"), aur="masscan", blackarch="masscan", legal="lab"),
    Pkg("wireshark", (RoleId.CYBER, RoleId.OPS, RoleId.DEVELOPER),
        "Analisi pacchetti catturati da te", "Analyze packets you captured",
        n("wireshark", debian="wireshark"), legal="lab"),
    Pkg("tcpdump", (RoleId.CYBER, RoleId.OPS),
        "Cattura pacchetti", "Packet capture", n("tcpdump"), legal="lab"),
    Pkg("tshark", (RoleId.CYBER, RoleId.OPS),
        "Wireshark CLI", "Wireshark CLI",
        n("tshark", arch="wireshark-cli", fedora="wireshark-cli"), legal="lab"),
    Pkg("aircrack-ng", (RoleId.CYBER,),
        "Audit Wi-Fi su reti tue/autorizzate", "Wi-Fi audit on your/authorized nets",
        n("aircrack-ng"), legal="lab"),
    Pkg("hashcat", (RoleId.CYBER,),
        "Recupero hash tuoi / da engagement", "Recover your hashes / engagement hashes",
        n("hashcat"), heavy=True, legal="lab"),
    Pkg("john", (RoleId.CYBER,),
        "John the Ripper (stessi limiti di hashcat)", "John the Ripper (same limits as hashcat)",
        n("john", fedora="john"), legal="lab"),
    Pkg("sqlmap", (RoleId.CYBER,),
        "SQLi su applicazioni in scope", "SQLi on in-scope apps",
        n("sqlmap"), blackarch="sqlmap", legal="lab"),
    Pkg("gobuster", (RoleId.CYBER,),
        "Enum contenuto web in scope", "Web content enum in scope",
        n("gobuster"), aur="gobuster", blackarch="gobuster", legal="lab"),
    Pkg("ffuf", (RoleId.CYBER,),
        "Fuzzing HTTP in scope", "HTTP fuzzing in scope",
        n("ffuf"), aur="ffuf", blackarch="ffuf", legal="lab"),
    Pkg("nikto", (RoleId.CYBER,),
        "Check configurazione web", "Web config checks",
        n("nikto"), blackarch="nikto", legal="lab"),
    Pkg("hydra", (RoleId.CYBER,),
        "Password spraying su lab/in-scope", "Password spraying on lab/in-scope",
        n("hydra", debian="hydra", ubuntu="hydra", fedora="hydra"),
        blackarch="thc-hydra", legal="lab"),
    Pkg("binwalk", (RoleId.CYBER, RoleId.DEVELOPER),
        "Firmware / file carving", "Firmware / file carving",
        n("binwalk"), legal="lab"),
    Pkg("radare2", (RoleId.CYBER, RoleId.DEVELOPER),
        "Reverse engineering (binari tuoi o in scope)", "RE (your binaries or in-scope)",
        n("radare2"), legal="lab"),
    Pkg("gdb-peda", (RoleId.CYBER, RoleId.DEVELOPER),
        "Helper gdb (lab)", "gdb helpers (lab)",
        n(None, kali="gdb-peda", debian=None), aur="gdb-peda", recommended=False, legal="lab"),
    Pkg("exploitdb", (RoleId.CYBER,),
        "searchsploit: archivio pubblico di riferimento", "searchsploit: public reference archive",
        n(None, kali="exploitdb"), blackarch="exploitdb", kali_only=False, legal="lab"),
    Pkg("metasploit-framework", (RoleId.CYBER,),
        "Framework di assessment su target autorizzati", "Assessment framework on authorized targets",
        n(None, kali="metasploit-framework"), blackarch="metasploit",
        heavy=True, legal="lab"),
    Pkg("burpsuite", (RoleId.CYBER,),
        "Proxy HTTP Community (licenza PortSwigger)", "HTTP proxy Community (PortSwigger license)",
        n(None, kali="burpsuite"), aur="burpsuite", heavy=True, legal="lab"),
    Pkg("impacket", (RoleId.CYBER,),
        "Librerie Windows lab (impacket)", "Windows lab libraries (impacket)",
        n("python3-impacket", arch="impacket", fedora="python3-impacket", kali="python3-impacket"),
        pipx="impacket", legal="lab"),
    Pkg("netcat", (RoleId.CYBER, RoleId.OPS, RoleId.DEVELOPER),
        "TCP/UDP debug", "TCP/UDP debug",
        n("netcat-openbsd", arch="gnu-netcat", fedora="nmap-ncat", kali="netcat-traditional",
          alpine="netcat-openbsd"), legal="lab"),
    Pkg("socat", (RoleId.CYBER, RoleId.OPS),
        "Relay socket", "Socket relay", n("socat"), legal="lab"),
    Pkg("enum4linux", (RoleId.CYBER,),
        "Enum SMB in scope", "SMB enum in scope",
        n("enum4linux", fedora=None), blackarch="enum4linux", legal="lab"),
    Pkg("smbclient", (RoleId.CYBER, RoleId.OPS),
        "Client SMB", "SMB client",
        n("smbclient", arch="smbclient", fedora="samba-client"), legal="lab"),
    Pkg("dnsutils", (RoleId.CYBER, RoleId.OPS, RoleId.DEVELOPER),
        "dig / nslookup", "dig / nslookup",
        n("dnsutils", arch="bind", fedora="bind-utils", alpine="bind-tools", kali="dnsutils"), legal="lab"),
    Pkg("whois", (RoleId.CYBER, RoleId.OPS),
        "WHOIS pubblico", "Public WHOIS", n("whois"), legal="lab"),
    Pkg("whatweb", (RoleId.CYBER,),
        "Fingerprint web in scope", "Web fingerprint in scope",
        n("whatweb"), blackarch="whatweb", legal="lab"),
    Pkg("nuclei", (RoleId.CYBER,),
        "Template scan su perimetro autorizzato", "Template scan on authorized perimeter",
        n(None, arch=None, kali=None), aur="nuclei", blackarch="nuclei", legal="lab"),
    Pkg("amass", (RoleId.CYBER,),
        "OSINT sottodomini passivo/attivo in scope", "Subdomain OSINT in scope",
        n(None), aur="amass", blackarch="amass", legal="lab"),
    Pkg("trivy", (RoleId.CYBER, RoleId.DEVELOPER, RoleId.OPS),
        "Scan vulnerabilità immagini/fs tue", "Vuln scan of your images/fs",
        n(None, arch="trivy", fedora="trivy"), aur="trivy", legal="lab"),
    Pkg("lynis", (RoleId.CYBER, RoleId.OPS, RoleId.PRIVACY, RoleId.SERVER),
        "Audit di hardening di QUESTA macchina", "Hardening audit of THIS machine",
        n("lynis"), legal="lab"),
    Pkg("chkrootkit", (RoleId.CYBER, RoleId.PRIVACY, RoleId.SERVER),
        "Controlli rootkit locali", "Local rootkit checks",
        n("chkrootkit"), legal="lab"),
    Pkg("clamav", (RoleId.CYBER, RoleId.PRIVACY, RoleId.DAILY),
        "Antivirus on-demand locale", "On-demand local AV",
        n("clamav"), heavy=True, legal="lab"),
    Pkg("yara", (RoleId.CYBER,),
        "Regole YARA su file tuoi", "YARA rules on your files",
        n("yara"), legal="lab"),
    Pkg("exiftool", (RoleId.CYBER, RoleId.CREATIVE, RoleId.DEVELOPER),
        "Metadati file", "File metadata",
        n("libimage-exiftool-perl", arch="perl-image-exiftool", fedora="perl-Image-ExifTool",
          alpine="exiftool", kali="libimage-exiftool-perl"), legal="lab"),
    Pkg("foremost", (RoleId.CYBER,),
        "File carving su immagini disco tue", "File carving on your disk images",
        n("foremost"), blackarch="foremost", recommended=False, legal="lab"),
    Pkg("sleuthkit", (RoleId.CYBER,),
        "Forensics su evidenze tue", "Forensics on your evidence",
        n("sleuthkit"), heavy=True, legal="lab"),
    Pkg("volatility3", (RoleId.CYBER,),
        "Memoria: dump tuoi", "Memory: your dumps",
        n(None, kali="volatility3"), pipx="volatility3", blackarch="volatility3",
        heavy=True, legal="lab"),
    Pkg("bettercap", (RoleId.CYBER,),
        "Lab di rete locale autorizzato", "Authorized local-net lab",
        n("bettercap"), blackarch="bettercap", legal="lab"),
    Pkg("responder", (RoleId.CYBER,),
        "LLMNR/NBT-NS in lab isolato", "LLMNR/NBT-NS in isolated lab",
        n(None, kali="responder"), blackarch="responder", legal="lab"),
    Pkg("wordlists", (RoleId.CYBER,),
        "Wordlist (rockyou ecc.) per lab", "Wordlists (rockyou etc.) for lab",
        n(None, kali="wordlists", debian=None), blackarch="wordlist", legal="lab"),
    Pkg("seclists", (RoleId.CYBER,),
        "SecLists", "SecLists",
        n(None, kali="seclists"), aur="seclists", blackarch="seclists", legal="lab"),
    # ── server extras ──────────────────────────────────────────────────
    Pkg("openssh-server", (RoleId.SERVER, RoleId.OPS),
        "sshd (solo se ti serve)", "sshd (only if you need it)",
        n("openssh-server", arch="openssh", fedora="openssh-server"), recommended=False),
    Pkg("cronie", (RoleId.SERVER, RoleId.OPS),
        "cron", "cron",
        n("cron", arch="cronie", fedora="cronie", debian="cron")),
)


def for_roles(roles: list[RoleId] | tuple[RoleId, ...]) -> tuple[Pkg, ...]:
    wanted = set(roles)
    if not wanted:
        return tuple()
    return tuple(p for p in PACKAGES if wanted.intersection(p.roles))


def by_id(pid: str) -> Pkg | None:
    for p in PACKAGES:
        if p.id == pid:
            return p
    return None


def name_for(pkg: Pkg, family: DistroFamily) -> str | None:
    return pkg.names.get(family) or pkg.names.get(DistroFamily.UNKNOWN)
